name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Yarn Install
        run: yarn install

      - name: Lint
        run: yarn run lint
      
      - name: Build
        run: yarn run build
      
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
  
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          cname: home.smnth.net
